### ISSUE TITLE
Actividad fuente de datos

### ISSUE THREAD

**Issue by SantiBaca** [MOOC-UNAM-Publico/curso-datos#3]
Equipo: Paola Collantes Ríos, Mariana Rojas, Mariana Carrillo, Santiago Baca y Kluk
¿Cuál es tu fuente de datos? (título, origen y enlace)
Título: Hospitales privados de la Zona Metropolitana del Valle de México
Origen: CDMX
Enlace: https://datos.cdmx.gob.mx/dataset/hospitales-privados-de-la-zona-metropolitana-del-valle-de-mexico

¿Quién produjo tu fuente de datos?
El Instituto de Planeación Democrática y Prospectiva de la Ciudad de México es un organismo público descentralizado, que tiene por objeto la rectoría y conducción del proceso integral de planeación del desarrollo de la Ciudad, en coordinación con los demás entes de la Administración Pública Local, Alcaldías y la concurrencia participativa de los sectores académicos, culturales, sociales y económicos.

¿Cuál es la fecha de la última actualización de los datos?
Fecha de la última actualización de los datos: 25 de agosto 2022

¿En qué formato de archivo se encuentra disponible? (csv, json, Excel)
.csv y .shp
El csv es solo un diccionario. Tiene muchos datos importantes. El shp hay que descomprimirlo por qué está en zip y ya son datos geográficos etc

¿Por qué consideras que esta fuente de datos te será útil?
 Consideramos que esta fuente de información nos ayudó mucho, ya que cuenta con las categorías, formatos, licencias y toda la información necesaria que requeríamos para completar nuestra investigación. La información viene clara y concisa, con fuentes confiables que respaldan dicha información.

**Comment by jairomelo** [comment]
Hola @SantiBaca 

Ya que vamos a entrar en la parte relacionada con el procesamiento de los datos, sería bueno valorar esta fuente de datos, a menos que tengan la posibilidad de manipular los archivos `shp`. Mi sugerencia sería que exploraran la posibilidad o de otra fuente de datos **O** la manera de convertir estos archivos `shp` a csv para poderlos manipular **O** explorar la manera de transformarlos a través de un SIG como QGis o ArcGis.

Ya me dirán qué opción tomaron 😁
