### ISSUE TITLE
Actividad fuente de datos

### ISSUE THREAD

**Issue by Paolavel** [MOOC-UNAM-Publico/curso-datos#4]
Equipo: Dana Paola Velasco Ramírez y Brenda Chagary
¿Cuál es tu fuente de datos? (título, origen y enlace)
Título: Bilioteca digitla UNAM
Origen: CDMX
Enlace: https://www.bidi.unam.mx/

¿Quién produjo tu fuente de datos?
La Dirección General de Bibliotecas, UNAM, debido a la forzosa actualización, centrada en la digitalización de los documentos de estas 
¿Cuál es la fecha de la última actualización de los datos?
 Lunes 26 Septiembre 2022.
¿En qué formato de archivo se encuentra disponible? (csv, json, Excel)
. json, excel y .shp
¿Por qué consideras que esta fuente de datos te será útil?
Consideremos que el desarrollo de las tecnologías de información es un indicativo de la evolución de los sistemas de información.
Las bibliotecas virtuales son un paradigma del acceso a la información, una vez, que por medio de ellas, el usuario puede obtener en forma ágil un sinnúmero de información que va desde un artículo hasta una referencia bibliográfica. 
En especial, la aparición y uso de Internet han revolucionado el que hacer, a partir de los modelos tradicionales vigentes hasta el momento. Las bibliotecas virtuales son un recurso de información necesario para el acceso y manejo de información digitalizada.
Los últimos años son testigos de los esfuerzos que han hechos muchas organizaciones para potenciar su desarrollo. Sin embargo, es preciso mejorar la integración de los usuarios con estos sistemas, y es así como se propone un nuevo modelo teórico para el diseño de bibliotecas virtuales adaptables

**Comment by jairomelo** [comment]
Hola @Paolavel 

Aprovechando que vamos a iniciar con las actividades de procesamiento de datos, quería comentarte que sería bueno valorar tu fuente de información. Es decir, entiendo perfectamente la utilidad de una fuente como la biblioteca digital, pero no sé si sea posible obtener los datos de allí 🤔 

Para seguir en el área de bibliotecas, les propongo una fuente de información bastante manejable que pueden obtener desde el portal de datos abiertos del gobierno de México: https://datos.gob.mx/busca/dataset/espacios-culturales--directorio--bibliotecas-de-la-direccion-general-de-bibliotecas/resource/ec64a0cc-668b-412e-9f6e-49c7a50d47ed?inner_span=True

Quedo pendiente.
Saludos!
